// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for ErrorResponseErrorCode.
const (
	CONFLICT            ErrorResponseErrorCode = "CONFLICT"
	FORBIDDEN           ErrorResponseErrorCode = "FORBIDDEN"
	INSUFFICIENTBALANCE ErrorResponseErrorCode = "INSUFFICIENT_BALANCE"
	INTERNALERROR       ErrorResponseErrorCode = "INTERNAL_ERROR"
	INVALIDREQUEST      ErrorResponseErrorCode = "INVALID_REQUEST"
	NOTFOUND            ErrorResponseErrorCode = "NOT_FOUND"
	RATELIMITED         ErrorResponseErrorCode = "RATE_LIMITED"
	SERVICEUNAVAILABLE  ErrorResponseErrorCode = "SERVICE_UNAVAILABLE"
	UNAUTHORIZED        ErrorResponseErrorCode = "UNAUTHORIZED"
	UNPROCESSABLEENTITY ErrorResponseErrorCode = "UNPROCESSABLE_ENTITY"
)

// Valid indicates whether the value is a known member of the ErrorResponseErrorCode enum.
func (e ErrorResponseErrorCode) Valid() bool {
	switch e {
	case CONFLICT:
		return true
	case FORBIDDEN:
		return true
	case INSUFFICIENTBALANCE:
		return true
	case INTERNALERROR:
		return true
	case INVALIDREQUEST:
		return true
	case NOTFOUND:
		return true
	case RATELIMITED:
		return true
	case SERVICEUNAVAILABLE:
		return true
	case UNAUTHORIZED:
		return true
	case UNPROCESSABLEENTITY:
		return true
	default:
		return false
	}
}

// Defines values for MarketStatus.
const (
	MarketStatusACTIVE   MarketStatus = "ACTIVE"
	MarketStatusCLOSED   MarketStatus = "CLOSED"
	MarketStatusRESOLVED MarketStatus = "RESOLVED"
)

// Valid indicates whether the value is a known member of the MarketStatus enum.
func (e MarketStatus) Valid() bool {
	switch e {
	case MarketStatusACTIVE:
		return true
	case MarketStatusCLOSED:
		return true
	case MarketStatusRESOLVED:
		return true
	default:
		return false
	}
}

// Defines values for OrderStatus.
const (
	OrderStatusCANCELLED       OrderStatus = "CANCELLED"
	OrderStatusFILLED          OrderStatus = "FILLED"
	OrderStatusPARTIALLYFILLED OrderStatus = "PARTIALLY_FILLED"
	OrderStatusPENDING         OrderStatus = "PENDING"
)

// Valid indicates whether the value is a known member of the OrderStatus enum.
func (e OrderStatus) Valid() bool {
	switch e {
	case OrderStatusCANCELLED:
		return true
	case OrderStatusFILLED:
		return true
	case OrderStatusPARTIALLYFILLED:
		return true
	case OrderStatusPENDING:
		return true
	default:
		return false
	}
}

// Defines values for ResolveMarketResponseStatus.
const (
	ResolveMarketResponseStatusRESOLVED ResolveMarketResponseStatus = "RESOLVED"
)

// Valid indicates whether the value is a known member of the ResolveMarketResponseStatus enum.
func (e ResolveMarketResponseStatus) Valid() bool {
	switch e {
	case ResolveMarketResponseStatusRESOLVED:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	UserRoleAdmin     UserRole = "admin"
	UserRoleModerator UserRole = "moderator"
	UserRoleUser      UserRole = "user"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case UserRoleAdmin:
		return true
	case UserRoleModerator:
		return true
	case UserRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for ListMarketsParamsStatus.
const (
	ACTIVE   ListMarketsParamsStatus = "ACTIVE"
	CLOSED   ListMarketsParamsStatus = "CLOSED"
	RESOLVED ListMarketsParamsStatus = "RESOLVED"
)

// Valid indicates whether the value is a known member of the ListMarketsParamsStatus enum.
func (e ListMarketsParamsStatus) Valid() bool {
	switch e {
	case ACTIVE:
		return true
	case CLOSED:
		return true
	case RESOLVED:
		return true
	default:
		return false
	}
}

// Defines values for ListMarketsParamsSortBy.
const (
	CreatedAt ListMarketsParamsSortBy = "created_at"
	Deadline  ListMarketsParamsSortBy = "deadline"
	Liquidity ListMarketsParamsSortBy = "liquidity"
)

// Valid indicates whether the value is a known member of the ListMarketsParamsSortBy enum.
func (e ListMarketsParamsSortBy) Valid() bool {
	switch e {
	case CreatedAt:
		return true
	case Deadline:
		return true
	case Liquidity:
		return true
	default:
		return false
	}
}

// Defines values for GetMyOrdersParamsStatus.
const (
	GetMyOrdersParamsStatusCANCELLED       GetMyOrdersParamsStatus = "CANCELLED"
	GetMyOrdersParamsStatusFILLED          GetMyOrdersParamsStatus = "FILLED"
	GetMyOrdersParamsStatusPARTIALLYFILLED GetMyOrdersParamsStatus = "PARTIALLY_FILLED"
	GetMyOrdersParamsStatusPENDING         GetMyOrdersParamsStatus = "PENDING"
)

// Valid indicates whether the value is a known member of the GetMyOrdersParamsStatus enum.
func (e GetMyOrdersParamsStatus) Valid() bool {
	switch e {
	case GetMyOrdersParamsStatusCANCELLED:
		return true
	case GetMyOrdersParamsStatusFILLED:
		return true
	case GetMyOrdersParamsStatusPARTIALLYFILLED:
		return true
	case GetMyOrdersParamsStatusPENDING:
		return true
	default:
		return false
	}
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	// AccessToken JWT токен (15 мин)
	AccessToken string `json:"access_token"`

	// RefreshToken Refresh токен (30 дней)
	RefreshToken string `json:"refresh_token"`
	User         User   `json:"user"`
}

// Balance defines model for Balance.
type Balance struct {
	// Available Доступные средства
	Available float32 `json:"available"`

	// BlockedInOrders Заблокировано в активных ордерах
	BlockedInOrders float32 `json:"blocked_in_orders"`

	// Total Общий баланс
	Total float32 `json:"total"`
}

// CreateOrderRequest defines model for CreateOrderRequest.
type CreateOrderRequest struct {
	// MarketId ID рынка
	MarketId openapi_types.UUID `json:"market_id"`

	// Outcome Выбранный исход
	Outcome string `json:"outcome"`

	// Quantity Количество акций для покупки
	Quantity float32 `json:"quantity"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code ErrorResponseErrorCode `json:"code"`

		// Details Дополнительные детали ошибки
		Details *map[string]interface{} `json:"details,omitempty"`

		// Message Описание ошибки на русском
		Message string `json:"message"`
	} `json:"error"`
}

// ErrorResponseErrorCode defines model for ErrorResponse.Error.Code.
type ErrorResponseErrorCode string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// Market defines model for Market.
type Market struct {
	CreatedAt time.Time `json:"created_at"`

	// CreatedBy ID администратора, создавшего рынок
	CreatedBy *openapi_types.UUID `json:"created_by,omitempty"`

	// Deadline Deadline окончания торговли
	Deadline time.Time `json:"deadline"`

	// Description Полное описание события
	Description *string `json:"description,omitempty"`

	// Id Уникальный ID рынка
	Id openapi_types.UUID `json:"id"`

	// Outcomes Возможные исходы события
	Outcomes []string `json:"outcomes"`

	// ResolvedOutcome Выигравший исход (если RESOLVED)
	ResolvedOutcome *string `json:"resolved_outcome,omitempty"`

	// Status Статус рынка
	Status MarketStatus `json:"status"`

	// Title Название события
	Title string `json:"title"`
}

// MarketStatus Статус рынка
type MarketStatus string

// MarketsResponse defines model for MarketsResponse.
type MarketsResponse struct {
	Data *[]Market       `json:"data,omitempty"`
	Meta *PaginationMeta `json:"meta,omitempty"`
}

// Order defines model for Order.
type Order struct {
	// AmountPaid Общая сумма платежа
	AmountPaid float32            `json:"amount_paid"`
	CreatedAt  time.Time          `json:"created_at"`
	Id         openapi_types.UUID `json:"id"`
	MarketId   openapi_types.UUID `json:"market_id"`
	Outcome    string             `json:"outcome"`

	// Price Цена за одну акцию
	Price float32 `json:"price"`

	// Quantity Количество акций
	Quantity float32     `json:"quantity"`
	Status   OrderStatus `json:"status"`
}

// OrderStatus defines model for Order.Status.
type OrderStatus string

// OrdersResponse defines model for OrdersResponse.
type OrdersResponse struct {
	Data *[]Order        `json:"data,omitempty"`
	Meta *PaginationMeta `json:"meta,omitempty"`
}

// PaginationMeta defines model for PaginationMeta.
type PaginationMeta struct {
	Page    *int `json:"page,omitempty"`
	Pages   *int `json:"pages,omitempty"`
	PerPage *int `json:"per_page,omitempty"`
	Total   *int `json:"total,omitempty"`
}

// Position defines model for Position.
type Position struct {
	// AvgCost Средняя стоимость покупки
	AvgCost float32 `json:"avg_cost"`

	// CurrentValue Текущая стоимость позиции
	CurrentValue float32            `json:"current_value"`
	MarketId     openapi_types.UUID `json:"market_id"`

	// MarketTitle Название события
	MarketTitle string `json:"market_title"`

	// Outcome Ваш исход
	Outcome string `json:"outcome"`

	// Pnl Profit/Loss
	Pnl float32 `json:"pnl"`

	// Quantity Количество владеемых акций
	Quantity float32 `json:"quantity"`
}

// PositionsResponse defines model for PositionsResponse.
type PositionsResponse struct {
	Data *[]Position `json:"data,omitempty"`
	Meta *struct {
		TotalCurrentValue *float32 `json:"total_current_value,omitempty"`
		TotalInvested     *float32 `json:"total_invested,omitempty"`
		TotalPnl          *float32 `json:"total_pnl,omitempty"`
		TotalPositions    *int     `json:"total_positions,omitempty"`
	} `json:"meta,omitempty"`
}

// RefreshTokenRequest defines model for RefreshTokenRequest.
type RefreshTokenRequest struct {
	// RefreshToken Refresh токен, полученный при登录
	RefreshToken string `json:"refresh_token"`
}

// RefreshTokenResponse defines model for RefreshTokenResponse.
type RefreshTokenResponse struct {
	AccessToken string `json:"access_token"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	// Email Email пользователя (уникальный)
	Email openapi_types.Email `json:"email"`

	// Password Пароль минимум 8 символов
	Password string `json:"password"`
}

// ResolveMarketRequest defines model for ResolveMarketRequest.
type ResolveMarketRequest struct {
	// EvidenceUrl URL с доказательством исхода
	EvidenceUrl *string `json:"evidence_url,omitempty"`

	// WinningOutcome Выигравший исход
	WinningOutcome string `json:"winning_outcome"`
}

// ResolveMarketResponse defines model for ResolveMarketResponse.
type ResolveMarketResponse struct {
	MarketId   *openapi_types.UUID          `json:"market_id,omitempty"`
	ResolvedAt *time.Time                   `json:"resolved_at,omitempty"`
	Status     *ResolveMarketResponseStatus `json:"status,omitempty"`

	// TotalPayout Общая выплата победителям
	TotalPayout    *float32 `json:"total_payout,omitempty"`
	WinningOutcome *string  `json:"winning_outcome,omitempty"`
}

// ResolveMarketResponseStatus defines model for ResolveMarketResponse.Status.
type ResolveMarketResponseStatus string

// TradesResponse defines model for TradesResponse.
type TradesResponse struct {
	Data *[]struct {
		ExecutedAt  *time.Time          `json:"executed_at,omitempty"`
		Id          *openapi_types.UUID `json:"id,omitempty"`
		MarketId    *openapi_types.UUID `json:"market_id,omitempty"`
		MarketTitle *string             `json:"market_title,omitempty"`
		Outcome     *string             `json:"outcome,omitempty"`
		Pnl         *float32            `json:"pnl,omitempty"`
		Price       *float32            `json:"price,omitempty"`
		Quantity    *float32            `json:"quantity,omitempty"`
	} `json:"data,omitempty"`
	Meta *PaginationMeta `json:"meta,omitempty"`
}

// User defines model for User.
type User struct {
	CreatedAt time.Time           `json:"created_at"`
	Email     openapi_types.Email `json:"email"`
	Id        openapi_types.UUID  `json:"id"`

	// Role Роль пользователя
	Role UserRole `json:"role"`
}

// UserRole Роль пользователя
type UserRole string

// ListMarketsParams defines parameters for ListMarkets.
type ListMarketsParams struct {
	// Page Номер страницы
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Количество рынков на странице
	PerPage *int `form:"per_page,omitempty" json:"per_page,omitempty"`

	// Status Фильтр по статусу
	Status *ListMarketsParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// SortBy Сортировка
	SortBy *ListMarketsParamsSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`
}

// ListMarketsParamsStatus defines parameters for ListMarkets.
type ListMarketsParamsStatus string

// ListMarketsParamsSortBy defines parameters for ListMarkets.
type ListMarketsParamsSortBy string

// GetMyOrdersParams defines parameters for GetMyOrders.
type GetMyOrdersParams struct {
	Page    *int                     `form:"page,omitempty" json:"page,omitempty"`
	PerPage *int                     `form:"per_page,omitempty" json:"per_page,omitempty"`
	Status  *GetMyOrdersParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// GetMyOrdersParamsStatus defines parameters for GetMyOrders.
type GetMyOrdersParamsStatus string

// GetMyTradesParams defines parameters for GetMyTrades.
type GetMyTradesParams struct {
	Page    *int `form:"page,omitempty" json:"page,omitempty"`
	PerPage *int `form:"per_page,omitempty" json:"per_page,omitempty"`

	// MarketId Фильтр по рынку
	MarketId *openapi_types.UUID `form:"market_id,omitempty" json:"market_id,omitempty"`
}

// ResolveMarketJSONRequestBody defines body for ResolveMarket for application/json ContentType.
type ResolveMarketJSONRequestBody = ResolveMarketRequest

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = LoginRequest

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody = RefreshTokenRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = RegisterRequest

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody = CreateOrderRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Разрешить исход рынка (Admin/Moderator только)
	// (POST /api/admin/markets/{marketId}/resolve)
	ResolveMarket(w http.ResponseWriter, r *http.Request, marketId openapi_types.UUID)
	// Вход в систему
	// (POST /api/auth/login)
	LoginUser(w http.ResponseWriter, r *http.Request)
	// Выход из системы
	// (POST /api/auth/logout)
	LogoutUser(w http.ResponseWriter, r *http.Request)
	// Обновить JWT токен
	// (POST /api/auth/refresh)
	RefreshToken(w http.ResponseWriter, r *http.Request)
	// Регистрация нового пользователя
	// (POST /api/auth/register)
	RegisterUser(w http.ResponseWriter, r *http.Request)
	// Баланс счета
	// (GET /api/balance)
	GetBalance(w http.ResponseWriter, r *http.Request)
	// Список всех рынков
	// (GET /api/markets)
	ListMarkets(w http.ResponseWriter, r *http.Request, params ListMarketsParams)
	// Детали рынка
	// (GET /api/markets/{marketId})
	GetMarketDetails(w http.ResponseWriter, r *http.Request, marketId openapi_types.UUID)
	// Мои ордера
	// (GET /api/orders)
	GetMyOrders(w http.ResponseWriter, r *http.Request, params GetMyOrdersParams)
	// Разместить ордер (купить/продать акцию)
	// (POST /api/orders)
	CreateOrder(w http.ResponseWriter, r *http.Request)
	// Отменить ордер
	// (DELETE /api/orders/{orderId})
	CancelOrder(w http.ResponseWriter, r *http.Request, orderId openapi_types.UUID)
	// Мой портфель
	// (GET /api/positions)
	GetPositions(w http.ResponseWriter, r *http.Request)
	// История моих сделок
	// (GET /api/trades)
	GetMyTrades(w http.ResponseWriter, r *http.Request, params GetMyTradesParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Разрешить исход рынка (Admin/Moderator только)
// (POST /api/admin/markets/{marketId}/resolve)
func (_ Unimplemented) ResolveMarket(w http.ResponseWriter, r *http.Request, marketId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Вход в систему
// (POST /api/auth/login)
func (_ Unimplemented) LoginUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Выход из системы
// (POST /api/auth/logout)
func (_ Unimplemented) LogoutUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Обновить JWT токен
// (POST /api/auth/refresh)
func (_ Unimplemented) RefreshToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Регистрация нового пользователя
// (POST /api/auth/register)
func (_ Unimplemented) RegisterUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Баланс счета
// (GET /api/balance)
func (_ Unimplemented) GetBalance(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Список всех рынков
// (GET /api/markets)
func (_ Unimplemented) ListMarkets(w http.ResponseWriter, r *http.Request, params ListMarketsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Детали рынка
// (GET /api/markets/{marketId})
func (_ Unimplemented) GetMarketDetails(w http.ResponseWriter, r *http.Request, marketId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Мои ордера
// (GET /api/orders)
func (_ Unimplemented) GetMyOrders(w http.ResponseWriter, r *http.Request, params GetMyOrdersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Разместить ордер (купить/продать акцию)
// (POST /api/orders)
func (_ Unimplemented) CreateOrder(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Отменить ордер
// (DELETE /api/orders/{orderId})
func (_ Unimplemented) CancelOrder(w http.ResponseWriter, r *http.Request, orderId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Мой портфель
// (GET /api/positions)
func (_ Unimplemented) GetPositions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// История моих сделок
// (GET /api/trades)
func (_ Unimplemented) GetMyTrades(w http.ResponseWriter, r *http.Request, params GetMyTradesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ResolveMarket operation middleware
func (siw *ServerInterfaceWrapper) ResolveMarket(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "marketId" -------------
	var marketId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "marketId", chi.URLParam(r, "marketId"), &marketId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "marketId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResolveMarket(w, r, marketId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LoginUser operation middleware
func (siw *ServerInterfaceWrapper) LoginUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LogoutUser operation middleware
func (siw *ServerInterfaceWrapper) LogoutUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LogoutUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshToken operation middleware
func (siw *ServerInterfaceWrapper) RefreshToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterUser operation middleware
func (siw *ServerInterfaceWrapper) RegisterUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBalance operation middleware
func (siw *ServerInterfaceWrapper) GetBalance(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBalance(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMarkets operation middleware
func (siw *ServerInterfaceWrapper) ListMarkets(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMarketsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "per_page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "per_page", r.URL.Query(), &params.PerPage, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "per_page", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "sort_by" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort_by", r.URL.Query(), &params.SortBy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort_by", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMarkets(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMarketDetails operation middleware
func (siw *ServerInterfaceWrapper) GetMarketDetails(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "marketId" -------------
	var marketId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "marketId", chi.URLParam(r, "marketId"), &marketId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "marketId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMarketDetails(w, r, marketId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMyOrders operation middleware
func (siw *ServerInterfaceWrapper) GetMyOrders(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMyOrdersParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "per_page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "per_page", r.URL.Query(), &params.PerPage, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "per_page", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMyOrders(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOrder operation middleware
func (siw *ServerInterfaceWrapper) CreateOrder(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOrder(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelOrder operation middleware
func (siw *ServerInterfaceWrapper) CancelOrder(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "orderId" -------------
	var orderId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "orderId", chi.URLParam(r, "orderId"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orderId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelOrder(w, r, orderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPositions operation middleware
func (siw *ServerInterfaceWrapper) GetPositions(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPositions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMyTrades operation middleware
func (siw *ServerInterfaceWrapper) GetMyTrades(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMyTradesParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "per_page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "per_page", r.URL.Query(), &params.PerPage, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "per_page", Err: err})
		return
	}

	// ------------- Optional query parameter "market_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "market_id", r.URL.Query(), &params.MarketId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "market_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMyTrades(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/admin/markets/{marketId}/resolve", wrapper.ResolveMarket)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/login", wrapper.LoginUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/logout", wrapper.LogoutUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/refresh", wrapper.RefreshToken)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/register", wrapper.RegisterUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/balance", wrapper.GetBalance)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/markets", wrapper.ListMarkets)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/markets/{marketId}", wrapper.GetMarketDetails)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/orders", wrapper.GetMyOrders)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/orders", wrapper.CreateOrder)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/orders/{orderId}", wrapper.CancelOrder)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/positions", wrapper.GetPositions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/trades", wrapper.GetMyTrades)
	})

	return r
}

type ResolveMarketRequestObject struct {
	MarketId openapi_types.UUID `json:"marketId"`
	Body     *ResolveMarketJSONRequestBody
}

type ResolveMarketResponseObject interface {
	VisitResolveMarketResponse(w http.ResponseWriter) error
}

type ResolveMarket200JSONResponse ResolveMarketResponse

func (response ResolveMarket200JSONResponse) VisitResolveMarketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ResolveMarket400JSONResponse ErrorResponse

func (response ResolveMarket400JSONResponse) VisitResolveMarketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ResolveMarket401JSONResponse ErrorResponse

func (response ResolveMarket401JSONResponse) VisitResolveMarketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ResolveMarket403JSONResponse ErrorResponse

func (response ResolveMarket403JSONResponse) VisitResolveMarketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ResolveMarket404JSONResponse ErrorResponse

func (response ResolveMarket404JSONResponse) VisitResolveMarketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ResolveMarket409JSONResponse ErrorResponse

func (response ResolveMarket409JSONResponse) VisitResolveMarketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type ResolveMarket500JSONResponse ErrorResponse

func (response ResolveMarket500JSONResponse) VisitResolveMarketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ResolveMarket503JSONResponse ErrorResponse

func (response ResolveMarket503JSONResponse) VisitResolveMarketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type LoginUserRequestObject struct {
	Body *LoginUserJSONRequestBody
}

type LoginUserResponseObject interface {
	VisitLoginUserResponse(w http.ResponseWriter) error
}

type LoginUser200JSONResponse AuthResponse

func (response LoginUser200JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type LoginUser400JSONResponse ErrorResponse

func (response LoginUser400JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type LoginUser401JSONResponse ErrorResponse

func (response LoginUser401JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type LoginUser429JSONResponse ErrorResponse

func (response LoginUser429JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response)
}

type LoginUser500JSONResponse ErrorResponse

func (response LoginUser500JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type LogoutUserRequestObject struct {
}

type LogoutUserResponseObject interface {
	VisitLogoutUserResponse(w http.ResponseWriter) error
}

type LogoutUser204Response struct {
}

func (response LogoutUser204Response) VisitLogoutUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type LogoutUser401JSONResponse ErrorResponse

func (response LogoutUser401JSONResponse) VisitLogoutUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type LogoutUser500JSONResponse ErrorResponse

func (response LogoutUser500JSONResponse) VisitLogoutUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RefreshTokenRequestObject struct {
	Body *RefreshTokenJSONRequestBody
}

type RefreshTokenResponseObject interface {
	VisitRefreshTokenResponse(w http.ResponseWriter) error
}

type RefreshToken200JSONResponse RefreshTokenResponse

func (response RefreshToken200JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RefreshToken401JSONResponse ErrorResponse

func (response RefreshToken401JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type RefreshToken403JSONResponse ErrorResponse

func (response RefreshToken403JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type RefreshToken500JSONResponse ErrorResponse

func (response RefreshToken500JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RegisterUserRequestObject struct {
	Body *RegisterUserJSONRequestBody
}

type RegisterUserResponseObject interface {
	VisitRegisterUserResponse(w http.ResponseWriter) error
}

type RegisterUser201JSONResponse AuthResponse

func (response RegisterUser201JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type RegisterUser400JSONResponse ErrorResponse

func (response RegisterUser400JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RegisterUser409JSONResponse ErrorResponse

func (response RegisterUser409JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type RegisterUser422JSONResponse ErrorResponse

func (response RegisterUser422JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type RegisterUser500JSONResponse ErrorResponse

func (response RegisterUser500JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetBalanceRequestObject struct {
}

type GetBalanceResponseObject interface {
	VisitGetBalanceResponse(w http.ResponseWriter) error
}

type GetBalance200JSONResponse Balance

func (response GetBalance200JSONResponse) VisitGetBalanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetBalance401JSONResponse ErrorResponse

func (response GetBalance401JSONResponse) VisitGetBalanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetBalance404JSONResponse ErrorResponse

func (response GetBalance404JSONResponse) VisitGetBalanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetBalance500JSONResponse ErrorResponse

func (response GetBalance500JSONResponse) VisitGetBalanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListMarketsRequestObject struct {
	Params ListMarketsParams
}

type ListMarketsResponseObject interface {
	VisitListMarketsResponse(w http.ResponseWriter) error
}

type ListMarkets200JSONResponse MarketsResponse

func (response ListMarkets200JSONResponse) VisitListMarketsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListMarkets400JSONResponse ErrorResponse

func (response ListMarkets400JSONResponse) VisitListMarketsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListMarkets429JSONResponse ErrorResponse

func (response ListMarkets429JSONResponse) VisitListMarketsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response)
}

type ListMarkets500JSONResponse ErrorResponse

func (response ListMarkets500JSONResponse) VisitListMarketsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetMarketDetailsRequestObject struct {
	MarketId openapi_types.UUID `json:"marketId"`
}

type GetMarketDetailsResponseObject interface {
	VisitGetMarketDetailsResponse(w http.ResponseWriter) error
}

type GetMarketDetails200JSONResponse Market

func (response GetMarketDetails200JSONResponse) VisitGetMarketDetailsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMarketDetails400JSONResponse ErrorResponse

func (response GetMarketDetails400JSONResponse) VisitGetMarketDetailsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetMarketDetails404JSONResponse ErrorResponse

func (response GetMarketDetails404JSONResponse) VisitGetMarketDetailsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetMarketDetails500JSONResponse ErrorResponse

func (response GetMarketDetails500JSONResponse) VisitGetMarketDetailsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetMyOrdersRequestObject struct {
	Params GetMyOrdersParams
}

type GetMyOrdersResponseObject interface {
	VisitGetMyOrdersResponse(w http.ResponseWriter) error
}

type GetMyOrders200JSONResponse OrdersResponse

func (response GetMyOrders200JSONResponse) VisitGetMyOrdersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMyOrders401JSONResponse ErrorResponse

func (response GetMyOrders401JSONResponse) VisitGetMyOrdersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetMyOrders500JSONResponse ErrorResponse

func (response GetMyOrders500JSONResponse) VisitGetMyOrdersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateOrderRequestObject struct {
	Body *CreateOrderJSONRequestBody
}

type CreateOrderResponseObject interface {
	VisitCreateOrderResponse(w http.ResponseWriter) error
}

type CreateOrder201JSONResponse Order

func (response CreateOrder201JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateOrder400JSONResponse ErrorResponse

func (response CreateOrder400JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateOrder401JSONResponse ErrorResponse

func (response CreateOrder401JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateOrder402JSONResponse ErrorResponse

func (response CreateOrder402JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(402)

	return json.NewEncoder(w).Encode(response)
}

type CreateOrder404JSONResponse ErrorResponse

func (response CreateOrder404JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreateOrder409JSONResponse ErrorResponse

func (response CreateOrder409JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreateOrder422JSONResponse ErrorResponse

func (response CreateOrder422JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type CreateOrder500JSONResponse ErrorResponse

func (response CreateOrder500JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CancelOrderRequestObject struct {
	OrderId openapi_types.UUID `json:"orderId"`
}

type CancelOrderResponseObject interface {
	VisitCancelOrderResponse(w http.ResponseWriter) error
}

type CancelOrder204Response struct {
}

func (response CancelOrder204Response) VisitCancelOrderResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type CancelOrder400JSONResponse ErrorResponse

func (response CancelOrder400JSONResponse) VisitCancelOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CancelOrder401JSONResponse ErrorResponse

func (response CancelOrder401JSONResponse) VisitCancelOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CancelOrder403JSONResponse ErrorResponse

func (response CancelOrder403JSONResponse) VisitCancelOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type CancelOrder404JSONResponse ErrorResponse

func (response CancelOrder404JSONResponse) VisitCancelOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CancelOrder409JSONResponse ErrorResponse

func (response CancelOrder409JSONResponse) VisitCancelOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CancelOrder500JSONResponse ErrorResponse

func (response CancelOrder500JSONResponse) VisitCancelOrderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetPositionsRequestObject struct {
}

type GetPositionsResponseObject interface {
	VisitGetPositionsResponse(w http.ResponseWriter) error
}

type GetPositions200JSONResponse PositionsResponse

func (response GetPositions200JSONResponse) VisitGetPositionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPositions401JSONResponse ErrorResponse

func (response GetPositions401JSONResponse) VisitGetPositionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetPositions404JSONResponse ErrorResponse

func (response GetPositions404JSONResponse) VisitGetPositionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetPositions500JSONResponse ErrorResponse

func (response GetPositions500JSONResponse) VisitGetPositionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetMyTradesRequestObject struct {
	Params GetMyTradesParams
}

type GetMyTradesResponseObject interface {
	VisitGetMyTradesResponse(w http.ResponseWriter) error
}

type GetMyTrades200JSONResponse TradesResponse

func (response GetMyTrades200JSONResponse) VisitGetMyTradesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMyTrades401JSONResponse ErrorResponse

func (response GetMyTrades401JSONResponse) VisitGetMyTradesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetMyTrades500JSONResponse ErrorResponse

func (response GetMyTrades500JSONResponse) VisitGetMyTradesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Разрешить исход рынка (Admin/Moderator только)
	// (POST /api/admin/markets/{marketId}/resolve)
	ResolveMarket(ctx context.Context, request ResolveMarketRequestObject) (ResolveMarketResponseObject, error)
	// Вход в систему
	// (POST /api/auth/login)
	LoginUser(ctx context.Context, request LoginUserRequestObject) (LoginUserResponseObject, error)
	// Выход из системы
	// (POST /api/auth/logout)
	LogoutUser(ctx context.Context, request LogoutUserRequestObject) (LogoutUserResponseObject, error)
	// Обновить JWT токен
	// (POST /api/auth/refresh)
	RefreshToken(ctx context.Context, request RefreshTokenRequestObject) (RefreshTokenResponseObject, error)
	// Регистрация нового пользователя
	// (POST /api/auth/register)
	RegisterUser(ctx context.Context, request RegisterUserRequestObject) (RegisterUserResponseObject, error)
	// Баланс счета
	// (GET /api/balance)
	GetBalance(ctx context.Context, request GetBalanceRequestObject) (GetBalanceResponseObject, error)
	// Список всех рынков
	// (GET /api/markets)
	ListMarkets(ctx context.Context, request ListMarketsRequestObject) (ListMarketsResponseObject, error)
	// Детали рынка
	// (GET /api/markets/{marketId})
	GetMarketDetails(ctx context.Context, request GetMarketDetailsRequestObject) (GetMarketDetailsResponseObject, error)
	// Мои ордера
	// (GET /api/orders)
	GetMyOrders(ctx context.Context, request GetMyOrdersRequestObject) (GetMyOrdersResponseObject, error)
	// Разместить ордер (купить/продать акцию)
	// (POST /api/orders)
	CreateOrder(ctx context.Context, request CreateOrderRequestObject) (CreateOrderResponseObject, error)
	// Отменить ордер
	// (DELETE /api/orders/{orderId})
	CancelOrder(ctx context.Context, request CancelOrderRequestObject) (CancelOrderResponseObject, error)
	// Мой портфель
	// (GET /api/positions)
	GetPositions(ctx context.Context, request GetPositionsRequestObject) (GetPositionsResponseObject, error)
	// История моих сделок
	// (GET /api/trades)
	GetMyTrades(ctx context.Context, request GetMyTradesRequestObject) (GetMyTradesResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ResolveMarket operation middleware
func (sh *strictHandler) ResolveMarket(w http.ResponseWriter, r *http.Request, marketId openapi_types.UUID) {
	var request ResolveMarketRequestObject

	request.MarketId = marketId

	var body ResolveMarketJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ResolveMarket(ctx, request.(ResolveMarketRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ResolveMarket")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ResolveMarketResponseObject); ok {
		if err := validResponse.VisitResolveMarketResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// LoginUser operation middleware
func (sh *strictHandler) LoginUser(w http.ResponseWriter, r *http.Request) {
	var request LoginUserRequestObject

	var body LoginUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LoginUser(ctx, request.(LoginUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LoginUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginUserResponseObject); ok {
		if err := validResponse.VisitLoginUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// LogoutUser operation middleware
func (sh *strictHandler) LogoutUser(w http.ResponseWriter, r *http.Request) {
	var request LogoutUserRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LogoutUser(ctx, request.(LogoutUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LogoutUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutUserResponseObject); ok {
		if err := validResponse.VisitLogoutUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RefreshToken operation middleware
func (sh *strictHandler) RefreshToken(w http.ResponseWriter, r *http.Request) {
	var request RefreshTokenRequestObject

	var body RefreshTokenJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshToken(ctx, request.(RefreshTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshToken")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RefreshTokenResponseObject); ok {
		if err := validResponse.VisitRefreshTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterUser operation middleware
func (sh *strictHandler) RegisterUser(w http.ResponseWriter, r *http.Request) {
	var request RegisterUserRequestObject

	var body RegisterUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterUser(ctx, request.(RegisterUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterUserResponseObject); ok {
		if err := validResponse.VisitRegisterUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetBalance operation middleware
func (sh *strictHandler) GetBalance(w http.ResponseWriter, r *http.Request) {
	var request GetBalanceRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetBalance(ctx, request.(GetBalanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBalance")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetBalanceResponseObject); ok {
		if err := validResponse.VisitGetBalanceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListMarkets operation middleware
func (sh *strictHandler) ListMarkets(w http.ResponseWriter, r *http.Request, params ListMarketsParams) {
	var request ListMarketsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListMarkets(ctx, request.(ListMarketsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListMarkets")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListMarketsResponseObject); ok {
		if err := validResponse.VisitListMarketsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMarketDetails operation middleware
func (sh *strictHandler) GetMarketDetails(w http.ResponseWriter, r *http.Request, marketId openapi_types.UUID) {
	var request GetMarketDetailsRequestObject

	request.MarketId = marketId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMarketDetails(ctx, request.(GetMarketDetailsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMarketDetails")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMarketDetailsResponseObject); ok {
		if err := validResponse.VisitGetMarketDetailsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMyOrders operation middleware
func (sh *strictHandler) GetMyOrders(w http.ResponseWriter, r *http.Request, params GetMyOrdersParams) {
	var request GetMyOrdersRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMyOrders(ctx, request.(GetMyOrdersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMyOrders")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMyOrdersResponseObject); ok {
		if err := validResponse.VisitGetMyOrdersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateOrder operation middleware
func (sh *strictHandler) CreateOrder(w http.ResponseWriter, r *http.Request) {
	var request CreateOrderRequestObject

	var body CreateOrderJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateOrder(ctx, request.(CreateOrderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateOrder")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateOrderResponseObject); ok {
		if err := validResponse.VisitCreateOrderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CancelOrder operation middleware
func (sh *strictHandler) CancelOrder(w http.ResponseWriter, r *http.Request, orderId openapi_types.UUID) {
	var request CancelOrderRequestObject

	request.OrderId = orderId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CancelOrder(ctx, request.(CancelOrderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CancelOrder")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CancelOrderResponseObject); ok {
		if err := validResponse.VisitCancelOrderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPositions operation middleware
func (sh *strictHandler) GetPositions(w http.ResponseWriter, r *http.Request) {
	var request GetPositionsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPositions(ctx, request.(GetPositionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPositions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPositionsResponseObject); ok {
		if err := validResponse.VisitGetPositionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMyTrades operation middleware
func (sh *strictHandler) GetMyTrades(w http.ResponseWriter, r *http.Request, params GetMyTradesParams) {
	var request GetMyTradesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMyTrades(ctx, request.(GetMyTradesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMyTrades")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMyTradesResponseObject); ok {
		if err := validResponse.VisitGetMyTradesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
